language: node_js
node_js:
  - 'node'

sudo: false

script: npm test

jobs:
  include:
    - stage: test
      addons:
        firefox: "latest-esr"
      script:
        - TEST_BROWSERS=Firefox,ChromeHeadless xvfb-run npm run all
    - stage: update examples
      script: './tasks/stages/update-examples'

stages:
  - test
  - name: update examples
    if: tag =~ ^v\d